project:
  type: website

website:
  title: "Advent of Code"
  site-url: https://adventofcode.ellakaye.co.uk
  description: Ella Kaye's solutions to Advent of Code
  repo-url: https://github.com/EllaKaye/advent-of-code
  navbar:
    left:
      - text: "2020"
        href: 2020.qmd
      - text: "2022"
        href: 2022.qmd
      - text: "2023"
        href: 2023.qmd
    right:
      - icon: github
        href: https://github.com/EllaKaye/advent-of-code
      - icon: person-circle
        href: https://ellakaye.co.uk
  open-graph: true

execute:
  freeze: auto
  echo: true
  message: false
  warning: false

format:
  html:
    theme: 
      light: assets/ek-theme-light.scss
      dark: assets/ek-theme-dark.scss
    css: assets/ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: assets/ek-light.theme
      dark: assets/ek-dark.theme
    smooth-scroll: true
    link-external-newwindow: true

editor: source



