---
title: "Advent of Code"
subtitle: "Ella Kaye's solutions and notes."
#description: "Ella Kaye's solutions and notes for Advent of Code."
---

[Advent of Code](https://adventofcode.com) is a series of increasingly difficult programming challenges, 
released daily each year throughout December in the run-up to Christmas.

This website is created from the 
[EllaKaye/advent-of-code](https://github.com/EllaKaye/advent-of-code) repository.
I use it to keep a record of my solutions and make notes about what I learn along the way. 
It is built with [Quarto](https://quarto.org) and supported by my [**aochelpers**](https://github.com/EllaKaye/aochelpers) package. 
**aochelpers** provides functions to create the posts and listings pages, 
to download and read in the puzzle inputs, 
and other functions that are useful in	solving the puzzles 
(with more to be added as I work through the challenges).

If you would like a similar site, you can use the template at [EllaKaye/advent-of-code-website-template](https://github.com/EllaKaye/advent-of-code-website-template). Websites from this template work hand-in-hand with **aochelpers**.

The idea for this site came from seeing [Emil Hvitfeldt's version](https://emilhvitfeldt.github.io/rstats-adventofcode/) and **aochelpers** adapts and builds upon code from David Robinson's [adventdrob](https://github.com/dgrtwo/adventdrob) package.

The styling is based on my [personal site](https://ellakaye.co.uk).



