---
title: "2022: Day 6"
date: 2022-12-6
author: 
  - name: Ella Kaye
categories: [base R, strings, loops]
draft: false
---

## Setup

[The original challenge](https://adventofcode.com/2022/day/6)

[My data](input){target="_blank"}

## Part 1

```{r}
#| echo: false
OK <- "2022" < 3000
# Will only evaluate next code block if an actual year has been substituted for the placeholder
```


```{r}
#| eval: !expr OK
library(aochelpers)
input <- aoc_input_vector(6, 2022)
```

```{r}
data <- strsplit(input, "") |> unlist() 


for (i in 4:length(data)) {
	
	last_4 <- data[(i-3):i]
	last_4_unique <- last_4 |> unique() |> length()
	
	if (last_4_unique == 4) {
		break
	}
}
i
```


## Part 2

```{r}
for (i in 14:length(data)) {
	
	last_14 <- data[(i-13):i]
	last_14_unique <- last_14 |> unique() |> length()
	
	if (last_14_unique == 14) {
		break
	}
}
i
```


##### Session info {.appendix}

<details><summary>Toggle</summary>

```{r}
#| echo: false
library(sessioninfo)
# save the session info as an object
pkg_session <- session_info(pkgs = "attached")

# get the quarto version
quarto_version <- system("quarto --version", intern = TRUE)

# inject the quarto info
pkg_session$platform$quarto <- paste(
  system("quarto --version", intern = TRUE), 
  "@", 
  quarto::quarto_path()
  )

# print it out
pkg_session
```

</details>





